# Generated by Django 3.2.24 on 2024-02-22 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('noofsem', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='datasettable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='logintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='studenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegisterNo', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('Phoneno', models.BigIntegerField()),
                ('email', models.IntegerField()),
                ('year', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.coursetable')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='topicstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('status', models.IntegerField()),
                ('staff', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='stafftable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Phoneno', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='')),
                ('qualification', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='projectnotificationstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('lastdate', models.DateField()),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.coursetable')),
            ],
        ),
        migrations.CreateModel(
            name='intrestingareastable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.stafftable')),
            ],
        ),
        migrations.CreateModel(
            name='feedbacktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='complainttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='chattable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ll', to='project_assistant.logintable')),
                ('TOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jj', to='project_assistant.logintable')),
            ],
        ),
    ]
