# Generated by Django 3.2.24 on 2024-02-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_assistant', '0002_auto_20240222_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicstable',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_assistant.stafftable'),
        ),
        migrations.AlterField(
            model_name='topicstable',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
